### Criação de categoria
POST http://localhost:3001/categorias/criar
Content-Type: application/json

{
    "nome" : "Dormir",
    "cor" : "#00fffa",
    "icone" : "Luz.png"
}

### Remover uma categoria
GET http://localhost:3001/categorias/remover/2

### Atualizar categoria (Cor)
GET http://localhost:3001/categorias/atualizar/3
Content-Type: application/json

{
    "nome" : "Acordar",
    "cor" : "#8ddeeb",
    "icone" : "Luz.png"
}

### Procurar categoria
GET http://localhost:3001/categorias/procurar/1

### Listar categorias
GET http://localhost:3001/categorias/listar