### Criação de tarefa
POST http://localhost:3001/tarefas/criar
Content-Type: application/json

{
    "nome" : "Trabalhar",
    "tempoIni" : "12:30",
    "tempoFim" : "18:00",
    "rotinaId" : null,
    "categoriaId" : 1,
    "lembreteId" : null
}

### Remoção de uma tarefa
GET http://localhost:3001/tarefas/remover/1

### Atualizar uma tarefa (Hora de início e fim)
GET http://localhost:3001/tarefas/atualizar/3
Content-Type: application/json

{
    "nome" : "Trabalhar",
    "tempoIni" : "12:00",
    "tempoFim" : "19:00",
    "rotinaId" : null,
    "categoriaId" : 1,
    "lembreteId" : null
}

### Procurar uma tarefa
GET http://localhost:3001/tarefas/procurar/2

### Listar todas as tarefas
GET http://localhost:3001/tarefas/listar