### Criar rotina
POST http://localhost:3000/rotinas/criar
Content-Type: application/json

{
    "nome" : "Semanal Padrão",
    "duracao" : "Diária"
}

### Remover rotina
GET http://localhost:3000/rotinas/remover/3

### Atualizar rotina (Tarefas)
GET http://localhost:3000/rotinas/atualizar/4
Content-Type: application/json

{
    "nome" : "Semana Padrão",
    "duracao" : "Mensal"
}

### Procurar tarefa
GET http://localhost:3000/rotinas/procurar/4

### Listar rotinas
GET http://localhost:3000/rotinas/listar